export const AREAS = [
  "Adyar",
  "Alwarpet",
  "Anna Nagar",
  "Besant Nagar",
  "Chepauk",
  "Gopalapuram",
  "Kottivakkam",
  "Kotturpuram",
  "Koyambedu",
  "Mandaveli",
  "Mylapore",
  "Mogappair",
  "MRC Nagar",
  "Nandanam",
  "Palavakkam",
  "Perungudi",
  "RA Puram",
  "Royapettah",
  "Santhome",
  "T.Nagar",
  "Teynampet",
  "Thiruvanmiyur",
  "West Mambalam",
];